mina:
    location:
      width: 25
      world: "mina"
    blocks:
      material:
        COAL_BLOCK:
          nivel: 0
          porcentage: 0.4
        CoAL_ORE:
          nivel: 5
          porcentage: 10.5
      xp-por-block: 1.0
      msg-on-break: "&bMina | &cVocê quebrou um bloco é recebeu {coins} coins"
      coin-por-block: 124.0

    skins:
      item:
        type: "EMERALD"
        name: "§aSkins"
        lore:
          - " "
          - "§7Clique com o botão direito"
          - "§7Para ganhar 1 nova skin"
          - " "
      inventory:
        name: "&cSkins"
        slots: 27

    pickaxe:
      name: "&cPicareta"
      lore:
        - " "
        - "Britadeira: {britadeira}/@max-level"
        - "Laser: {laser}/@max-level"
        - "Multiplicador: {multiplicador}/@max-level"
        - "Fortuna: {fortuna}/@max-level"
        - "Bonus: {bonus}/@max-level"
        - "Raio: {raio}/@max-level"
        - "XP Booster: {xpbooster}/@max-level"
        - "Explosão: {explosao}/@max-level"
        - " "
